import {NextResponse} from 'next/server';
import {revalidatePath} from 'next/cache';
import {owner} from '@/lib/supabase';
import {contentSchema,settingsSchema} from '@/lib/schema';
import {sameOrigin} from '@/lib/request';
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({message:'Invalid origin.'},{status:403});const auth=await owner();if(!auth)return NextResponse.json({message:'Owner access required.'},{status:401});let input;try{input=await req.json();}catch{return NextResponse.json({message:'Invalid request.'},{status:400});}const {kind,action,id}=input;const {db}=auth;let error;let resourceId=id;
if(kind==='settings'){const p=settingsSchema.safeParse(input.data);if(!p.success)return NextResponse.json({message:p.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('\n')},{status:400});if(action==='publish'){({error}=await db.rpc('publish_settings',{p_data:p.data}));}else if(action==='save'){({error}=await db.from('settings_revisions').upsert({state:'draft',data:p.data,updated_at:new Date().toISOString()},{onConflict:'state'}));}else return NextResponse.json({message:'Unknown action.'},{status:400});}
else if(['projects','playground_items','articles'].includes(kind)){if(!['save','publish','unpublish','delete'].includes(action))return NextResponse.json({message:'Unknown action.'},{status:400});if(['save','publish'].includes(action)){const p=contentSchema.safeParse(input.data);if(!p.success)return NextResponse.json({message:p.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('\n')},{status:400});if(!resourceId){const r=await db.from(kind).insert({seed:false}).select('id').single();if(r.error)return NextResponse.json({message:r.error.message},{status:400});resourceId=r.data.id;}if(action==='publish'){({error}=await db.rpc('publish_content',{p_table:kind,p_id:resourceId,p_data:p.data}));}else{({error}=await db.from(kind+'_revisions').upsert({resource_id:resourceId,state:'draft',data:p.data,updated_at:new Date().toISOString()},{onConflict:'resource_id,state'}));}}else if(action==='unpublish'){({error}=await db.from(kind+'_revisions').delete().eq('resource_id',id).eq('state','published'));}else{({error}=await db.from(kind).delete().eq('id',id));}}
else if(kind==='enquiries'){if(action==='delete')({error}=await db.from('enquiries').delete().eq('id',id));else if(action==='read'||action==='archive')({error}=await db.from('enquiries').update(action==='read'?{is_read:Boolean(input.value)}:{archived:Boolean(input.value)}).eq('id',id));else return NextResponse.json({message:'Unknown action.'},{status:400});}
else if(kind==='cleanup'){const tables=['projects','playground_items','articles'];if(action==='count'){const counts=await Promise.all(tables.map(async t=>{const r=await db.from(t).select('id',{count:'exact',head:true}).eq('seed',true);if(r.error)throw r.error;return {kind:t,count:r.count||0};}));return NextResponse.json({counts});}if(action==='clear'&&input.confirm==='CLEAR STARTER CONTENT'){for(const t of tables){const r=await db.from(t).delete().eq('seed',true);if(r.error){error=r.error;break;}}}else return NextResponse.json({message:'Confirmation is required.'},{status:400});}
else return NextResponse.json({message:'Unknown collection.'},{status:400});
if(error)return NextResponse.json({message:error.message},{status:400});revalidatePath('/','layout');return NextResponse.json({id:resourceId,message:action==='publish'?'Published. Your live site is updated.':action==='save'?'Draft saved. Your live site is unchanged.':'Changes saved.'});}
